name: check

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: true
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set test UDFs
        shell: bash
        run: ./scripts/test-vars.sh

      - name: Hack github actions runner for check mode
        shell: bash
        run: |-
          chown_list=(
          "/var/lib/apt"
          "/var/lib/update-notifier"
          "/var/lib/dpkg"
          "/var/cache/apt"
          "/var/cache/debconf"
          "/usr/bin/dpkg"
          "/dev/ttyS0"
          "/var/log"
          "/usr/local/bin"
          )

          for dir in "${chown_list[@]}"; do
            sudo chown -R $(whoami): $dir
            if [ "${dir}" != "/dev/ttyS0" ]; then
              sudo mkdir -p $dir
            fi
            
            if [ "${dir}" == "/usr/local/bin" ]; then
              echo "$dir" >> $GITHUB_PATH
            fi
          done

          declare -A ssh_dict
          ssh_dict["#ListenAddress 0.0.0.0"]="ListenAddress 0.0.0.0"
          ssh_dict["PermitRootLogin yes"]="PermitRootLogin no"
          ssh_dict["#PermitRootLogin no"]="PermitRootLogin no"
          ssh_dict["#PubkeyAuthentication yes"]="PubkeyAuthentication yes"
          ssh_dict["#PasswordAuthentication no"]="PasswordAuthentication no"
          ssh_dict["PasswordAuthentication yes"]="PasswordAuthentication no"
          ssh_dict["#PasswordAuthentication yes"]="PasswordAuthentication no"

          for conf in "${!ssh_dict[@]}"; do
            sudo sed -i -e "s/${conf}/${ssh_dict[$conf]}/g" /etc/ssh/sshd_config
          done
          sudo systemctl restart ssh
          
      - name: Run deploy script in check mode
        shell: bash
        run: |-
          sudo -i -u $(whoami)
          cd $GITHUB_WORKSPACE
          ./scripts/kafka-deploy.sh
        env:
          TOKEN_PASSWORD: r3@llystr0ngp455w0rd
          CHECK_MODE: 1

      - name: Setup tmate debugging session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true
        env:
          TOKEN_PASSWORD: r3@llystr0ngp455w0rd
          CHECK_MODE: 1
